-- Audit trail for PDF artifacts produced by the dispatch pipeline (metadata only; files live in Storage).

CREATE TABLE public.generated_documents (
  id uuid NOT NULL PRIMARY KEY DEFAULT gen_random_uuid(),
  dispatch_key text NOT NULL,
  case_id text NOT NULL,
  stripe_session_id text,
  email_to text NOT NULL,
  storage_bucket text NOT NULL,
  storage_path text NOT NULL,
  sha256 text,
  status text NOT NULL DEFAULT 'generated',
  provider text,
  provider_message_id text,
  sent_at timestamp with time zone,
  error_detail text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),

  CONSTRAINT generated_documents_case_id_format CHECK (case_id ~ '^CASO_'),
  CONSTRAINT generated_documents_status_check CHECK (
    status = ANY (ARRAY['generated'::text, 'emailed'::text, 'email_failed'::text])
  )
);

COMMENT ON TABLE public.generated_documents IS 'Metadata for PDFs generated by the pipeline; binaries live in Supabase Storage.';
COMMENT ON COLUMN public.generated_documents.email_to IS 'Snapshot of form_submissions.email at generation time';

CREATE UNIQUE INDEX generated_documents_dispatch_key_key
  ON public.generated_documents USING btree (dispatch_key);

CREATE UNIQUE INDEX generated_documents_bucket_path_key
  ON public.generated_documents USING btree (storage_bucket, storage_path);

CREATE INDEX idx_generated_documents_case_id
  ON public.generated_documents USING btree (case_id);

CREATE INDEX idx_generated_documents_status
  ON public.generated_documents USING btree (status);

CREATE INDEX idx_generated_documents_created_at
  ON public.generated_documents USING btree (created_at DESC);

CREATE INDEX idx_generated_documents_email_to
  ON public.generated_documents USING btree (email_to);

ALTER TABLE public.generated_documents
  ADD CONSTRAINT generated_documents_dispatch_key_fkey
  FOREIGN KEY (dispatch_key) REFERENCES public.dispatches (dispatch_key)
  ON DELETE RESTRICT;

ALTER TABLE public.generated_documents
  ADD CONSTRAINT generated_documents_stripe_session_id_fkey
  FOREIGN KEY (stripe_session_id) REFERENCES public.stripe_sessions (id)
  ON DELETE SET NULL;

ALTER TABLE public.generated_documents ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Service role can manage generated_documents"
  ON public.generated_documents
  FOR ALL
  USING (true)
  WITH CHECK (true);

CREATE TRIGGER generated_documents_set_updated_at
  BEFORE UPDATE ON public.generated_documents
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();
