// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tsdzvxgkokrjqayxukud.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRzZHp2eGdrb2tyanFheXh1a3VkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3NjEzNDUsImV4cCI6MjA3MjMzNzM0NX0.sl22MuovwUNy6iW-iwSXUrT7GHDbK608rKWEpxC0ex0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});